### ISSUE TITLE
BUG: Feather-related regression tests failing at head of master branch

### ISSUE THREAD

**Issue by frreiss** [CODAIT/text-extensions-for-pandas#28]
When I run `python -m unittest discover` at the head of the master branch, 5 regression tests related to Feather I/O fail. Output follows:

```
======================================================================
ERROR: test_feather (text_extensions_for_pandas.array.test_char_span.CharSpanArrayIOTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/freiss/pd/tep-conll-4/text_extensions_for_pandas/array/test_char_span.py", line 396, in test_feather
    pd.testing.assert_frame_equal(df, df_read)
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pandas/_testing.py", line 1382, in assert_frame_equal
    obj=f'{obj}.iloc[:, {i}] (column name="{col}")',
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pandas/_testing.py", line 1184, in assert_series_equal
    assert_extension_array_equal(left.array, right.array)
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pandas/_testing.py", line 1034, in assert_extension_array_equal
    right_valid = np.asarray(right[~right_na].astype(object))
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pandas/core/arrays/base.py", line 443, in astype
    return np.array(self, dtype=dtype, copy=copy)
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pandas/core/arrays/base.py", line 352, in __iter__
    yield self[i]
  File "/Users/freiss/pd/tep-conll-4/text_extensions_for_pandas/array/char_span.py", line 297, in __getitem__
    int(self._ends[item]))
  File "/Users/freiss/pd/tep-conll-4/text_extensions_for_pandas/array/char_span.py", line 65, in __init__
    raise ValueError(f"end must be less than length of target string "
ValueError: end must be less than length of target string (32 > 15

======================================================================
ERROR: test_feather (text_extensions_for_pandas.array.test_tensor.TensorArrayIOTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/freiss/pd/tep-conll-4/text_extensions_for_pandas/array/test_tensor.py", line 346, in test_feather
    df_read = pd.read_feather(filename)
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pandas/io/feather_format.py", line 103, in read_feather
    return feather.read_feather(path, columns=columns, use_threads=bool(use_threads))
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pyarrow/feather.py", line 214, in read_feather
    return (read_table(source, columns=columns, memory_map=memory_map)
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pyarrow/feather.py", line 239, in read_table
    return reader.read()
  File "pyarrow/feather.pxi", line 79, in pyarrow.lib.FeatherReader.read
  File "pyarrow/public-api.pxi", line 390, in pyarrow.lib.pyarrow_wrap_table
  File "pyarrow/error.pxi", line 85, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Column 1: In chunk 0: Invalid: List child array invalid: Invalid: Buffer #1 too small in array of type int64 and length 10: expected at least 80 byte(s), got 68

======================================================================
ERROR: test_feather_auto_chunked (text_extensions_for_pandas.array.test_tensor.TensorArrayIOTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/freiss/pd/tep-conll-4/text_extensions_for_pandas/array/test_tensor.py", line 399, in test_feather_auto_chunked
    table = read_table(filename)
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pyarrow/feather.py", line 239, in read_table
    return reader.read()
  File "pyarrow/feather.pxi", line 79, in pyarrow.lib.FeatherReader.read
  File "pyarrow/public-api.pxi", line 390, in pyarrow.lib.pyarrow_wrap_table
  File "pyarrow/error.pxi", line 85, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Column 1: In chunk 0: Invalid: List child array invalid: Invalid: Buffer #1 too small in array of type int64 and length 1024: expected at least 8192 byte(s), got 4121

======================================================================
ERROR: test_feather_chunked (text_extensions_for_pandas.array.test_tensor.TensorArrayIOTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/freiss/pd/tep-conll-4/text_extensions_for_pandas/array/test_tensor.py", line 381, in test_feather_chunked
    df_read = pd.read_feather(filename)
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pandas/io/feather_format.py", line 103, in read_feather
    return feather.read_feather(path, columns=columns, use_threads=bool(use_threads))
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pyarrow/feather.py", line 214, in read_feather
    return (read_table(source, columns=columns, memory_map=memory_map)
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pyarrow/feather.py", line 239, in read_table
    return reader.read()
  File "pyarrow/feather.pxi", line 79, in pyarrow.lib.FeatherReader.read
  File "pyarrow/public-api.pxi", line 390, in pyarrow.lib.pyarrow_wrap_table
  File "pyarrow/error.pxi", line 85, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Column 1: In chunk 0: Invalid: List child array invalid: Invalid: Buffer #1 too small in array of type int64 and length 10: expected at least 80 byte(s), got 68

======================================================================
ERROR: test_feather (text_extensions_for_pandas.array.test_token_span.TokenSpanArrayIOTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/freiss/pd/tep-conll-4/text_extensions_for_pandas/array/test_token_span.py", line 341, in test_feather
    self.do_roundtrip(df1)
  File "/Users/freiss/pd/tep-conll-4/text_extensions_for_pandas/array/test_token_span.py", line 333, in do_roundtrip
    pd.testing.assert_frame_equal(df, df_read)
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pandas/_testing.py", line 1382, in assert_frame_equal
    obj=f'{obj}.iloc[:, {i}] (column name="{col}")',
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pandas/_testing.py", line 1184, in assert_series_equal
    assert_extension_array_equal(left.array, right.array)
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pandas/_testing.py", line 1034, in assert_extension_array_equal
    right_valid = np.asarray(right[~right_na].astype(object))
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pandas/core/arrays/base.py", line 443, in astype
    return np.array(self, dtype=dtype, copy=copy)
  File "/Users/freiss/opt/miniconda3/envs/pd/lib/python3.7/site-packages/pandas/core/arrays/base.py", line 352, in __iter__
    yield self[i]
  File "/Users/freiss/pd/tep-conll-4/text_extensions_for_pandas/array/token_span.py", line 311, in __getitem__
    self._tokens, int(self._begin_tokens[item]), int(self._end_tokens[item])
  File "/Users/freiss/pd/tep-conll-4/text_extensions_for_pandas/array/token_span.py", line 71, in __init__
    f"Begin token offset of {begin_token} larger than "
ValueError: Begin token offset of 32 larger than number of tokens (4)

----------------------------------------------------------------------
Ran 87 tests in 1.751s

FAILED (errors=5, skipped=1)
```

**Comment by frreiss** [comment]
@BryanCutler  can you please have a look at these test failures?

**Comment by BryanCutler** [comment]
Sure, will take a look

**Comment by BryanCutler** [comment]
It seems like it is being written with compression, but the reader fails to account for that. The feather writer defaults to 'lz4' if available, and patching the pandas `feather_format` to be `feather.write_feather(df, path, compression="uncompressed")` gets tests passing again.  Will look into it further

**Comment by BryanCutler** [comment]
This seems to be the issue: https://issues.apache.org/jira/browse/ARROW-8860

**Comment by BryanCutler** [comment]
@frreiss are you using pyarrow 0.17.1?  This is when compression by default was added. I reverted to 0.17.0 and tests pass again.

**Comment by BryanCutler** [comment]
@frreiss were you able to verify reverting to arrow 0.17.0 fixes the tests?

**Comment by frreiss** [comment]
Oh, sorry, missed that last message. Thanks for pinging me! Yes, reverting to `pyarrow==0.17.0` fixes these problems. I'll put in a PR that adjusts `env.sh` momentarily.

**Comment by frreiss** [comment]
PR opened.

**Comment by BryanCutler** [comment]
Closing for now with workaround from #35
